### ISSUE TITLE
vim-tags has error at rebuildTagFiles()

### ISSUE THREAD

**Issue by TimothyWrightSoftware** [szw/vim-tags#18]
"src\nov-2015-1gam.cpp" 165L, 3701C written
Error detected while processing function AutoTag:
line    1:
WARNING:root:Traceback (most recent call last):
  File "C:\Users\Daddy007\vimfiles\bundle\vim-autotag\plugin\autotag.py", line 262, in autotag
    at.rebuildTagFiles()
  File "C:\Users\Daddy007\vimfiles\bundle\vim-autotag\plugin\autotag.py", line 253, in rebuildTagFiles
    self.updateTagsFile(tags_dir, tags_file, sources)
  File "C:\Users\Daddy007\vimfiles\bundle\vim-autotag\plugin\autotag.py", line 247, in updateTagsFile
    for l in do_cmd(cmd, self.tags_dir or tags_dir):
  File "C:\Users\Daddy007\vimfiles\bundle\vim-autotag\plugin\autotag.py", line 54, in do_cmd
    cwd=cwd)
  File "C:\Python27\Lib\subprocess.py", line 702, in **init**
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "C:\Python27\Lib\subprocess.py", line 833, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\Python27\Lib\subprocess.py", line 884, in _make_inheritable
    _subprocess.DUPLICATE_SAME_ACCESS)
WindowsError: [Error 6] The handle is invalid

E484: Can't open file :messages

**Comment by szw** [comment]
Hi!, I'm afraid it's not that plugin. Try to contact vim-autotag author instead.
